name: Build, Push & Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Name and Tag
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/pixelpainter:${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME -f Games/pixelpainter/Dockerfile Games/pixelpainter/

      - name: Push Image to Docker Hub
        run: docker push $IMAGE_NAME

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.SSH_USERNAME }}  # Set to 'ubuntu' for Ubuntu EC2
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/pixelpainter:${GITHUB_SHA::8}
            sudo docker stop pixelpainter-container || true
            sudo docker rm pixelpainter-container || true
            sudo docker run -d --name pixelpainter-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/pixelpainter:${GITHUB_SHA::8}
