name: Build, Push & Deploy Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Create a hardcoded tag instead of using SHA for simplicity
      - name: Build and Push Docker Image
        run: |
          export IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/pixelpainter:latest"
          docker build -t $IMAGE_NAME -f Games/pixelpainter/Dockerfile Games/pixelpainter/
          docker push $IMAGE_NAME
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Use a hardcoded image name to eliminate variable substitution issues
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/pixelpainter:latest
            
            # Stop and remove container if it exists
            sudo docker stop pixelpainter-container || true
            sudo docker rm pixelpainter-container || true
            
            # Run the new container with explicit image name
            sudo docker run -d --name pixelpainter-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/pixelpainter:latest
